### ISSUE TITLE
Website is dead?

### ISSUE THREAD

**Issue by neilpanchal** [s9w/font_compare#1]
Just tried accessing: https://s9w.github.io/font_compare/ with a blank page.

**Comment by ghost** [comment]
If you have any sort of adblock/third-party-script blocking, try unblocking `fb.me`. It was blank for me as well until I unblocked it.

**Comment by s9w** [comment]
The site is built with React which is loaded from fb.me. I could switch to another cdn like cdnjs.com, maybe that would help with adblock issues. I'll do it later today

edit: Better now? da13d9f38022ea02d8c05be607efccc161a59de5

**Comment by neilpanchal** [comment]
@CrystalDave @s9w Thanks for the tips. It's working now.
