### ISSUE TITLE
Add hyphen en dash em dash comparison

### ISSUE THREAD

**Issue by quicknir** [s9w/font_compare#10]
Hey, I recently got burned by Source Code Pro having a hyphen-minus and en dash that looked virtually identical. By "burned" I literally mean wasting an entire day trying to debug a Nagios server setup. It would be great to compare these three characters as well, ideally vertically with a comment beside. Their unicode sequences are: U+002D, U+2013, and U+2014 respectively.

**Comment by s9w** [comment]
Good idea, I'll add it!

**Comment by quicknir** [comment]
One other minor bit of feedback: I noted that some fonts do not show some of the text in bold, despite having bold versions available. I'm not sure why this is, but it is handy. It's a bit ridiculous but I've discovered that some "mono" fonts actually have a bold version that is wider. That is, its only mono if you don't mix widths. I think ubuntu mono is this way., notice that "render" in ubuntu mono is not bolded in your program. These fonts are worthless to me (and I suspect many people), your program would be a superb way of quickly finding these fonts out as you have a mixture of bold and regular font.

Finally, I'd like to say thanks, this project greatly shorted my search time for a new mono font (Roboto!). Great work!

**Comment by s9w** [comment]
I've added the dashes but made a mistake rendering yesterday, so it'll be tonight I think.

The boldness or lack thereof is an annoyance. Some fonts simply don't render their bold versions, others have bold versions as a separate font(-file), which doesn't help at all. I should probably look into if that can be improved with another editor (Atom maybe). I haven't even noticed that some bold fonts are wider - that's certainly not ideal!
