### ISSUE TITLE
Add SF Mono

### ISSUE THREAD

**Issue by kevinSuttle** [s9w/font_compare#16]
In XCode 8 Beta, SF Mono was introduced.

Located at: 
`Xcode-beta.app/Contents/SharedFrameworks/DVTKit.framework/Versions/A/Resources/Fonts/`

via https://www.designernews.co/stories/70545-monospace-san-francisco-typeface-direct-download-link

**Comment by s9w** [comment]
Wow, that font seems super bold. Capturing right now, will be up soon. Thanks for the tip!

**Comment by s9w** [comment]
This font was odd. Seems to be super italic by default. Also there is a drastic difference between the different renderers. If it weren't for the italic style, I would really like it.

**Comment by kevinSuttle** [comment]
I didn't have that issue, but it _did_ take several tries to install it. Got it eventually, though.

![https://cldup.com/wUpo36bT2T.png](https://cldup.com/wUpo36bT2T.png)

![https://cldup.com/EGx3o4_h9P.png](https://cldup.com/EGx3o4_h9P.png)

**Comment by jrvianna** [comment]
How did you deal with the "serious errors" during validation? Simply ignored?

**Comment by kevinSuttle** [comment]
I tried a different source (the one from designernews.co), but _didn't_ install. Then, I tried installing the ones from XCode again. The proverbial 'jiggling of the handle' as it were.
