### ISSUE TITLE
Andale Mono

### ISSUE THREAD

**Issue by TraderStf** [s9w/font_compare#5]
Andale Mono is great for coding.

I have an iMac 5K 27", still need help for captures?

**Comment by s9w** [comment]
Thanks for the tip! I found a "basic" version online, but a proper version with bold etc is not available as a free version, right? I can add that basic version though.

The high-dpi stuff has been taken care off. But my internet is damaged again (praise the developing nation Germany), so both of these patches will have to wait some hours or a bit longer.

**Comment by TraderStf** [comment]
Will search for Andale, so many sites with free stuff or free for individual...

I don't know where your problem is, but some VPN are showing faster speed on same 'cable'...
My 55GB line reach 65 GB when my VPN is on!

**Comment by TraderStf** [comment]
Andale Mono was included with MS IE 4, https://en.wikipedia.org/wiki/Andale_Mono
was replaced by Lucida Console, another one for your list.

Now seems available for 70$... still looking...

**Comment by TraderStf** [comment]
That's were I probably got it, OS X 10.7
https://en.wikipedia.org/wiki/List_of_typefaces_included_with_OS_X

**Comment by TraderStf** [comment]
Here v2.00 but seems only to exist in Regular, the WT/G version seems to have bold also.
http://web.nickshanks.com/fonts/microsoft-core-web-fonts
I did not read the 30000 pages license.
On my mac I have v2.00x (size: 109.700 - Police TrueType® OpenType®)
It is not in the HD/System/Library but in HD/Library.
But since 1984...... I don't remember all files' origin 😜

**Comment by TraderStf** [comment]
Seems to be copyrighted, other 'free' are included with OS... the other available are illegal copies.
Most were removed by 'request of © owner'.

Several sites recommend this alternative
http://www.typewolf.com/site-of-the-day/fonts/apercu-mono

**Comment by s9w** [comment]
I can add the basic Andale Mono version, everything else seems to be difficult. Apercu is a 50 dollar font if I read that correctly.

**Comment by s9w** [comment]
The regular Andale Mono is in, but without mono or italic styles since those seem to be impossible to find.

I've also contacted the creators of Apercu to see if they want to provide the font for this site. Otherwise I don't see this happening without some kind of donations or crowdfindung :D

**Comment by s9w** [comment]
No luck with Apercu apparently, but Andale is in so I'll close this.
