### ISSUE TITLE
Additional font sizes

### ISSUE THREAD

**Issue by tomzorz** [s9w/font_compare#6]
Could you implement additional sizes at 11, 12 and 13pt? 10 is too small, but 20 is too big to see how it'd look like "in action".

Thanks! (awesome idea / site btw :) )

**Comment by s9w** [comment]
You mean in overview? There are more sizes to chose from when you go to the compare mode

**Comment by tomzorz** [comment]
Yes, I meant in overview, sorry.

**Comment by s9w** [comment]
Hmm well that would be possible, I think that would be overkill to be honest. I was thinking that the default (small) size would be about the average size. There are many more sizes in the compare mode. Is that not enough?

Another way might be to change the overview sizes from 10/20 to 12/24

**Comment by tomzorz** [comment]
My main issue is that in compare mode you can only see one font at a time. Therefore I can't actually compare how a single line looks like with a given font size with multiple fonts at the same time.

**Comment by s9w** [comment]
Hmm okay. Would an increase from 10 to 12 solve that issue? Have a look at those sizes for Source Code Pro, that's the font I always use as a reference because it behaves the most sane of all.

**Comment by tomzorz** [comment]
I guess :) Also now I realized, that these lines are actually images so now I understand why it's not that easy to do this.

**Comment by s9w** [comment]
I've resized the small from 10 to 12 ( 702c2fc882f23c2ba69a79b646157ea55e1448c3 ). All good now? Actually I like it better now, thanks for the input!

**Comment by tomzorz** [comment]
Awesome! :)
