### ISSUE TITLE
please add glyphs …•×·∕– and —

### ISSUE THREAD

**Issue by mark-kubacki** [s9w/font_compare#7]
This should make a good overview if Unicode is supported at all.

–…— are used in English (and German), and shouldn't have the same length as - (minus)
•× are math symbols used in some niches
·∕ are typed when writing Assembly for the tools of language Go

Thanks!

**Comment by s9w** [comment]
Huh, never seen those last two, interesting. I'll add it, but I'll need some days. Thanks for the suggestion!

**Comment by s9w** [comment]
I've added …,• and × in 0711057581ab9e88dc131bbb011310afea4b6717

Not sure about the rest. They seem so exotic and there are so many unicode characters. I won't rule it out to add them, but maybe the unicode and potential ligature stuff should be done another way.

**Comment by mark-kubacki** [comment]
Nice, thanks!
