### ISSUE TITLE
1000 free opentype fonts until Sept. 6

### ISSUE THREAD

**Issue by TraderStf** [s9w/font_compare#8]
https://stacksocial.com/sales/free-1000-opentype-fonts
normally 99$
I suppose you can find few for programming :-)

To give me few bucks, you can use this link instead.
https://stacksocial.com/?rid=1465893

**Comment by s9w** [comment]
Anything interesting in it? Seems not to be about programming fonts

**Comment by TraderStf** [comment]
For those interested, it downloads the fonts folder, you are not obliged to install them.
I have checked them quickly, only 9 are non-proportional (some are weird) but none with zero different then letter O.
Useless then for dev, but some beautiful ones for other usages.

**Comment by TraderStf** [comment]
Just to say that the other free set of 623 fonts, from macappware, does not contain any non-prop. font.
Also few gorgeous but not for programming.

https://s3.amazonaws.com/128bittech/free/v3h7rtx4/FreeFonts_MacAppware.zip
